### ISSUE TITLE
A sane build system, maybe?

### ISSUE THREAD

**Issue by makerimages** [Vild/PowerNex#10]
Implementing a Makefile can't be that hard, the current buildscripts are just... ugh.  If you don't know how to get a Makefile up and running, ask the #osdev IRC. Mine was largely figured out by @ExeTwezz, for an example.

**Comment by Vild** [comment]
I have been planing for this for some time now.
Like I want a kconfig type of configuring, because it looks kewl. But I don't need it.
The current one is based on http://wiki.osdev.org/User:Solar/Makefile . But I broke the design of it when I added all the tools to the root Makefile.

Will probably use plain Makefile(s), maybe mixed with ninja (Because it's kewl & fast).
And then maybe add some sort of config thingy.

**Comment by makerimages** [comment]
Great! This will definately boost your OS's ease of testing for others-
